FROM oven/bun:1.3.11-alpine AS deps

WORKDIR /app

COPY package.json bun.lock ./
RUN bun install --frozen-lockfile

COPY . .

FROM mcr.microsoft.com/playwright:v1.58.2-noble

WORKDIR /app

COPY --from=deps /app /app

CMD ["npx", "playwright", "test", "tests/form-submit.spec.ts", "--config=playwright.config.ts", "--reporter=line"]
