import type { TFunction } from "i18next";

export enum Gender {
  MALE = "MALE",
  FEMALE = "FEMALE",
}

export enum TypeMovement {
  ON_FOOT = "ON_FOOT",
  TRANSPORT = "TRANSPORT",
}

export enum SocialStatus {
  WORKING = "WORKING",
  STUDENT = "STUDENT",
  UNIVERSITY_STUDENT = "UNIVERSITY_STUDENT",
  PENSIONER = "PENSIONER",
  PERSON_WITH_DISABILITIES = "PERSON_WITH_DISABILITIES",
  UNEMPLOYED = "UNEMPLOYED",
  HOUSEWIFE = "HOUSEWIFE",
  TEMPORARILY_UNEMPLOYED = "TEMPORARILY_UNEMPLOYED",
}

export enum Place {
  HOME_RESIDENCE = "HOME_RESIDENCE",
  FRIENDS_RELATIVES_HOME = "FRIENDS_RELATIVES_HOME",
  WORKPLACE = "WORKPLACE",
  WORK_BUSINESS_TRIP = "WORK_BUSINESS_TRIP",
  DAYCARE_CENTER = "DAYCARE_CENTER",
  SCHOOL = "SCHOOL",
  COLLEGE_TECHNICAL_SCHOOL = "COLLEGE_TECHNICAL_SCHOOL",
  UNIVERSITY_INSTITUTE = "UNIVERSITY_INSTITUTE",
  HOSPITAL_CLINIC = "HOSPITAL_CLINIC",
  CULTURAL_INSTITUTION = "CULTURAL_INSTITUTION",
  SPORT_FITNESS = "SPORT_FITNESS",
  STORE_MARKET = "STORE_MARKET",
  SHOPPING_ENTERTAINMENT_CENTER = "SHOPPING_ENTERTAINMENT_CENTER",
  RESTAURANT_CAFE = "RESTAURANT_CAFE",
  SUBURB = "SUBURB",
  OTHER = "OTHER",
}

export enum Transport {
  BICYCLE = "BICYCLE",
  INDIVIDUAL_MOBILITY = "INDIVIDUAL_MOBILITY",
  BUS = "BUS",
  SHUTTLE_TAXI = "SHUTTLE_TAXI",
  TRAM = "TRAM",
  PRIVATE_CAR = "PRIVATE_CAR",
  TROLLEYBUS = "TROLLEYBUS",
  SUBURBAN_TRAIN = "SUBURBAN_TRAIN",
  METRO = "METRO",
  TAXI = "TAXI",
  CAR_SHARING = "CAR_SHARING",
  CITY_BIKE_RENTAL = "CITY_BIKE_RENTAL",
  SERVICE = "SERVICE",
}

/**
 * Converts a string-valued enum to localized options for select controls.
 */
export function enumToOptions<T extends Record<string, string>>(
  inputEnum: T,
  t: TFunction,
  prefix: string,
): { value: string; label: string }[] {
  return Object.values(inputEnum).map((value) => ({
    value,
    label: t(`${prefix}.${value}`),
  }));
}
